version: '2'

services:
  app:
    build: .
    command: rails server -p 3000 -b 0.0.0.0
    volumes:
      - D:\Code\MovieApp:/usr/src/app/app
# Publish port 3000 - Not required if going via NGINX
#    ports:
#      - "3000:3000"
    links:
      - db

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
# Publish port 5432 - For development
#    ports:
#      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - 80:80
      - 443:443

volumes:
  db-data:
